# 三未信安协签服务器配置
[EasySSL]
ip=10.81.2.16              # 协签服务地址
port=2443                  # 协签服务端口
usessl=1                   # 使用 SSL 连接
loglevel=6                 # 日志等级
logfile=EasySSL.log        # 日志文件
keypath=./                 # 协签密钥的存储路径
certpath=./cert/sm2_client.pem
[EasySSLPool]
poolsize=10                # 连接池大小
[EasySSLTimeout]
connect=5                  # 连接超时
read=5                     # 读取超时
write=5                    # 发送超时