# 日志配置
[log]
file=./build/logs/error.log

# MAuth配置
[mauth]
# MAuth后台通信地址
host=10.81.2.3
# MAuth后台通信端口
port=20080
# MAuth连接、读写超时时间（默认：60；单位：秒）
timeout=5
# MAuth认证标识（由MAuth后台管理界面中获取）
appid=APP_01
# MAuth认证密钥（由MAuth后台管理界面中获取）
secret_key=H+7QGOq7gFBwIE5oZOgbaY9TNx0jjuegVI9dUjhKBW1hzMOsDMUrk5mteA97lhRUD8exhb9k60rKayOJgTyfLg==
# 密钥存放目录，用户密钥（默认：./datas/）
store_path=./build/datas/
# SSL开关（默认：on）
ssl=off
# SSL协议（默认：国密；国密："GMTLS", 国际："TLS"）
ssl_protocols=GMTLS
; ssl_protocols=TLS
# 根证书文件，若不设置，则不验证对端证书
; ssl_trusted_certificate="/root/kingdom/demo/resources/ca-bundle.crt"
; ssl_trusted_certificate="Z:\\kingdom\\demo\\resources\\ca-bundle.crt"
ssl_trusted_certificate=

# 通信配置
[net]
# 连接超时（默认：60s；单位：秒）
connect_timeout=5
# 读超时（默认：60s；单位：秒）
read_timeout=5
# 写超时（默认：60s；单位：秒）
write_timeout=5
# SSL开关（默认：on）
ssl=on
# SSL协议（默认：国密；国密："GMTLS", 国际："TLSv1.1 TLSv1.2 TLSv1.3"）
; ssl_protocols=GMTLS
; ssl_protocols=TLSv1.1 TLSv1.2 TLSv1.3
ssl_protocols=
# SSL套件（默认：根据协议自动指定；国密："ECC-SM4-SM3"，国际："ALL"）
; ssl_ciphers=ECC-SM4-SM3
; ssl_ciphers=ALL
ssl_ciphers=
# 根证书文件，若不设置，则不验证对端证书
; ssl_trusted_certificate="/root/kingdom/demo/resources/ca-bundle.crt"
; ssl_trusted_certificate="Z:\\kingdom\\demo\\resources\\ca-bundle.crt"
; ssl_trusted_certificate=/root/ssl/demo/resources/sm2.ca.pem
ssl_trusted_certificate=
